### ISSUE TITLE
got LangDetectException for Arabic Presentation Forms

### ISSUE THREAD

**Issue by mbande** [Mimino666/langdetect#22]
for both Arabic_Presentation_Forms-A and Arabic_Presentation_Forms-B characters, `detect` function throws exception:
```py
>> detect('ﺽ')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.5/site-packages/langdetect/detector_factory.py", line 130, in detect
    return detector.detect()
  File "/home/user/.local/lib/python3.5/site-packages/langdetect/detector.py", line 135, in detect
    probabilities = self.get_probabilities()
  File "/home/user/.local/lib/python3.5/site-packages/langdetect/detector.py", line 142, in get_probabilities
    self._detect_block()
  File "/home/user/.local/lib/python3.5/site-packages/langdetect/detector.py", line 149, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
```

**Comment by stoufa** [comment]
I have the same issue !

**Comment by stoufa** [comment]
After few searches I've found this [Stackoverflow post](https://stackoverflow.com/questions/10406135/unicodedecodeerror-ascii-codec-cant-decode-byte-0xd1-in-position-2-ordinal), you have to add these 3 lines of codes in your script
`import sys`
`reload(sys)`
`sys.setdefaultencoding('utf-8')`

and convert the text to unicode
`inputText = unicode(inputText)`
